export { prisma } from './client'
export * from './generated'
export * from './types'
export { seedCuentasParaguay } from './seed-cuentas-paraguay'
export { seedPlanCuentasParaguay } from './seed-plan-cuentas-paraguay' 